accounts:
  - name: alice
    coins: ["900000000ath", "900000000stake"]
  - name: bob
    coins: ["100000000ath", "100000000stake"]
validator:
  name: alice
  staked: "450000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["5ath", "100000stake"]
